build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      CYGWIN: C:\cygwin
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36
      CYGWIN: C:\cygwin
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37
      CYGWIN: C:\cygwin

init:
  - cmd: "ECHO %PYTHON_VERSION% %MINICONDA%"
  - cmd: "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - cmd: "set PATH=%PATH%;%CYGWIN%;%CYGWIN%\\bin"
  - cmd: "set PATH=C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64;%PATH%"
  

install:
  # - cmd: conda install -y matplotlib numpy scipy setuptools six pytest cython
  # Upgrade pip before we start installing packages
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install matplotlib --ignore-installed # use pip because conda install numpy fails with Python != 3.6
  - cmd: pip install numpy scipy setuptools six pytest cython 
  - cmd: python do.py run-python install-user
  - cmd: python do.py install-postprocessing

test_script:
  # run the experiment
  - cmd: cd code-experiments\build\python
  - cmd: python example_experiment.py bbob
  - cmd: python -m cocopp -o .\postproc .\exdata\random_search_on_bbob_budget0002xD
  - cmd: cd ..\..\..
  # run the tests
  - cmd: python do.py build-python
  - cmd: python do.py test-python
  - cmd: python do.py test-java
  - cmd: python do.py test-preprocessing
  - cmd: python do.py test-postprocessing
  - cmd: python do.py test-suites
  - cmd: python do.py test-c
  # - cmd: python do.py test-postprocessing-all
